// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/rider/rider.proto

package rider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiderService_CreateProfile_FullMethodName = "/rider.RiderService/CreateProfile"
	RiderService_GetProfile_FullMethodName    = "/rider.RiderService/GetProfile"
	RiderService_RequestRide_FullMethodName   = "/rider.RiderService/RequestRide"
	RiderService_GetMyTrips_FullMethodName    = "/rider.RiderService/GetMyTrips"
)

// RiderServiceClient is the client API for RiderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiderServiceClient interface {
	CreateProfile(ctx context.Context, in *CreateRiderProfileRequest, opts ...grpc.CallOption) (*CreateRiderProfileResponse, error)
	GetProfile(ctx context.Context, in *GetRiderProfileRequest, opts ...grpc.CallOption) (*RiderProfile, error)
	RequestRide(ctx context.Context, in *RequestRideRequest, opts ...grpc.CallOption) (*RequestRideResponse, error)
	GetMyTrips(ctx context.Context, in *GetRiderTripsRequest, opts ...grpc.CallOption) (*GetRiderTripsResponse, error)
}

type riderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiderServiceClient(cc grpc.ClientConnInterface) RiderServiceClient {
	return &riderServiceClient{cc}
}

func (c *riderServiceClient) CreateProfile(ctx context.Context, in *CreateRiderProfileRequest, opts ...grpc.CallOption) (*CreateRiderProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRiderProfileResponse)
	err := c.cc.Invoke(ctx, RiderService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderServiceClient) GetProfile(ctx context.Context, in *GetRiderProfileRequest, opts ...grpc.CallOption) (*RiderProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiderProfile)
	err := c.cc.Invoke(ctx, RiderService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderServiceClient) RequestRide(ctx context.Context, in *RequestRideRequest, opts ...grpc.CallOption) (*RequestRideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestRideResponse)
	err := c.cc.Invoke(ctx, RiderService_RequestRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderServiceClient) GetMyTrips(ctx context.Context, in *GetRiderTripsRequest, opts ...grpc.CallOption) (*GetRiderTripsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiderTripsResponse)
	err := c.cc.Invoke(ctx, RiderService_GetMyTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiderServiceServer is the server API for RiderService service.
// All implementations must embed UnimplementedRiderServiceServer
// for forward compatibility.
type RiderServiceServer interface {
	CreateProfile(context.Context, *CreateRiderProfileRequest) (*CreateRiderProfileResponse, error)
	GetProfile(context.Context, *GetRiderProfileRequest) (*RiderProfile, error)
	RequestRide(context.Context, *RequestRideRequest) (*RequestRideResponse, error)
	GetMyTrips(context.Context, *GetRiderTripsRequest) (*GetRiderTripsResponse, error)
	mustEmbedUnimplementedRiderServiceServer()
}

// UnimplementedRiderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiderServiceServer struct{}

func (UnimplementedRiderServiceServer) CreateProfile(context.Context, *CreateRiderProfileRequest) (*CreateRiderProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedRiderServiceServer) GetProfile(context.Context, *GetRiderProfileRequest) (*RiderProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedRiderServiceServer) RequestRide(context.Context, *RequestRideRequest) (*RequestRideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestRide not implemented")
}
func (UnimplementedRiderServiceServer) GetMyTrips(context.Context, *GetRiderTripsRequest) (*GetRiderTripsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyTrips not implemented")
}
func (UnimplementedRiderServiceServer) mustEmbedUnimplementedRiderServiceServer() {}
func (UnimplementedRiderServiceServer) testEmbeddedByValue()                      {}

// UnsafeRiderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiderServiceServer will
// result in compilation errors.
type UnsafeRiderServiceServer interface {
	mustEmbedUnimplementedRiderServiceServer()
}

func RegisterRiderServiceServer(s grpc.ServiceRegistrar, srv RiderServiceServer) {
	// If the following call panics, it indicates UnimplementedRiderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiderService_ServiceDesc, srv)
}

func _RiderService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRiderProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).CreateProfile(ctx, req.(*CreateRiderProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiderProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).GetProfile(ctx, req.(*GetRiderProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderService_RequestRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).RequestRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_RequestRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).RequestRide(ctx, req.(*RequestRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderService_GetMyTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiderTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderServiceServer).GetMyTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderService_GetMyTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderServiceServer).GetMyTrips(ctx, req.(*GetRiderTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiderService_ServiceDesc is the grpc.ServiceDesc for RiderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rider.RiderService",
	HandlerType: (*RiderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfile",
			Handler:    _RiderService_CreateProfile_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _RiderService_GetProfile_Handler,
		},
		{
			MethodName: "RequestRide",
			Handler:    _RiderService_RequestRide_Handler,
		},
		{
			MethodName: "GetMyTrips",
			Handler:    _RiderService_GetMyTrips_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rider/rider.proto",
}
