// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/rider/rider.proto

package rider

import (
	shared "github.com/taxxy/shared/proto/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRiderProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRiderProfileRequest) Reset() {
	*x = CreateRiderProfileRequest{}
	mi := &file_proto_rider_rider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRiderProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRiderProfileRequest) ProtoMessage() {}

func (x *CreateRiderProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_rider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRiderProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateRiderProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_rider_rider_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRiderProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRiderProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRiderProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateRiderProfileRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CreateRiderProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRiderProfileResponse) Reset() {
	*x = CreateRiderProfileResponse{}
	mi := &file_proto_rider_rider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRiderProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRiderProfileResponse) ProtoMessage() {}

func (x *CreateRiderProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_rider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRiderProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateRiderProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_rider_rider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRiderProfileResponse) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *CreateRiderProfileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetRiderProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderProfileRequest) Reset() {
	*x = GetRiderProfileRequest{}
	mi := &file_proto_rider_rider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderProfileRequest) ProtoMessage() {}

func (x *GetRiderProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_rider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderProfileRequest.ProtoReflect.Descriptor instead.
func (*GetRiderProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_rider_rider_proto_rawDescGZIP(), []int{2}
}

func (x *GetRiderProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RiderProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalRides    int32                  `protobuf:"varint,6,opt,name=total_rides,json=totalRides,proto3" json:"total_rides,omitempty"`
	AverageRating float64                `protobuf:"fixed64,7,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderProfile) Reset() {
	*x = RiderProfile{}
	mi := &file_proto_rider_rider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderProfile) ProtoMessage() {}

func (x *RiderProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_rider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderProfile.ProtoReflect.Descriptor instead.
func (*RiderProfile) Descriptor() ([]byte, []int) {
	return file_proto_rider_rider_proto_rawDescGZIP(), []int{3}
}

func (x *RiderProfile) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RiderProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RiderProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiderProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RiderProfile) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *RiderProfile) GetTotalRides() int32 {
	if x != nil {
		return x.TotalRides
	}
	return 0
}

func (x *RiderProfile) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

type RequestRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pickup        *shared.Location       `protobuf:"bytes,2,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *shared.Location       `protobuf:"bytes,3,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	VehicleType   string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRideRequest) Reset() {
	*x = RequestRideRequest{}
	mi := &file_proto_rider_rider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRideRequest) ProtoMessage() {}

func (x *RequestRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_rider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRideRequest.ProtoReflect.Descriptor instead.
func (*RequestRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_rider_rider_proto_rawDescGZIP(), []int{4}
}

func (x *RequestRideRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestRideRequest) GetPickup() *shared.Location {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *RequestRideRequest) GetDropoff() *shared.Location {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *RequestRideRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

type RequestRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EstimatedFare float64                `protobuf:"fixed64,3,opt,name=estimated_fare,json=estimatedFare,proto3" json:"estimated_fare,omitempty"`
	Eta           string                 `protobuf:"bytes,4,opt,name=eta,proto3" json:"eta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRideResponse) Reset() {
	*x = RequestRideResponse{}
	mi := &file_proto_rider_rider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRideResponse) ProtoMessage() {}

func (x *RequestRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_rider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRideResponse.ProtoReflect.Descriptor instead.
func (*RequestRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_rider_rider_proto_rawDescGZIP(), []int{5}
}

func (x *RequestRideResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *RequestRideResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RequestRideResponse) GetEstimatedFare() float64 {
	if x != nil {
		return x.EstimatedFare
	}
	return 0
}

func (x *RequestRideResponse) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

type GetRiderTripsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderTripsRequest) Reset() {
	*x = GetRiderTripsRequest{}
	mi := &file_proto_rider_rider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderTripsRequest) ProtoMessage() {}

func (x *GetRiderTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_rider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderTripsRequest.ProtoReflect.Descriptor instead.
func (*GetRiderTripsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rider_rider_proto_rawDescGZIP(), []int{6}
}

func (x *GetRiderTripsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRiderTripsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRiderTripsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetRiderTripsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trips         []*RiderTripSummary    `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderTripsResponse) Reset() {
	*x = GetRiderTripsResponse{}
	mi := &file_proto_rider_rider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderTripsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderTripsResponse) ProtoMessage() {}

func (x *GetRiderTripsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_rider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderTripsResponse.ProtoReflect.Descriptor instead.
func (*GetRiderTripsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rider_rider_proto_rawDescGZIP(), []int{7}
}

func (x *GetRiderTripsResponse) GetTrips() []*RiderTripSummary {
	if x != nil {
		return x.Trips
	}
	return nil
}

func (x *GetRiderTripsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RiderTripSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Fare          float64                `protobuf:"fixed64,3,opt,name=fare,proto3" json:"fare,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderTripSummary) Reset() {
	*x = RiderTripSummary{}
	mi := &file_proto_rider_rider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderTripSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderTripSummary) ProtoMessage() {}

func (x *RiderTripSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rider_rider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderTripSummary.ProtoReflect.Descriptor instead.
func (*RiderTripSummary) Descriptor() ([]byte, []int) {
	return file_proto_rider_rider_proto_rawDescGZIP(), []int{8}
}

func (x *RiderTripSummary) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *RiderTripSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RiderTripSummary) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

func (x *RiderTripSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_rider_rider_proto protoreflect.FileDescriptor

const file_proto_rider_rider_proto_rawDesc = "" +
	"\n" +
	"\x17proto/rider/rider.proto\x12\x05rider\x1a\x19proto/shared/shared.proto\"\x85\x01\n" +
	"\x19CreateRiderProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\"O\n" +
	"\x1aCreateRiderProfileResponse\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"1\n" +
	"\x16GetRiderProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xdb\x01\n" +
	"\fRiderProfile\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vtotal_rides\x18\x06 \x01(\x05R\n" +
	"totalRides\x12%\n" +
	"\x0eaverage_rating\x18\a \x01(\x01R\raverageRating\"\xa6\x01\n" +
	"\x12RequestRideRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x06pickup\x18\x02 \x01(\v2\x10.shared.LocationR\x06pickup\x12*\n" +
	"\adropoff\x18\x03 \x01(\v2\x10.shared.LocationR\adropoff\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\"\x7f\n" +
	"\x13RequestRideResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0eestimated_fare\x18\x03 \x01(\x01R\restimatedFare\x12\x10\n" +
	"\x03eta\x18\x04 \x01(\tR\x03eta\"]\n" +
	"\x14GetRiderTripsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\\\n" +
	"\x15GetRiderTripsResponse\x12-\n" +
	"\x05trips\x18\x01 \x03(\v2\x17.rider.RiderTripSummaryR\x05trips\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"v\n" +
	"\x10RiderTripSummary\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04fare\x18\x03 \x01(\x01R\x04fare\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt2\xb5\x02\n" +
	"\fRiderService\x12T\n" +
	"\rCreateProfile\x12 .rider.CreateRiderProfileRequest\x1a!.rider.CreateRiderProfileResponse\x12@\n" +
	"\n" +
	"GetProfile\x12\x1d.rider.GetRiderProfileRequest\x1a\x13.rider.RiderProfile\x12D\n" +
	"\vRequestRide\x12\x19.rider.RequestRideRequest\x1a\x1a.rider.RequestRideResponse\x12G\n" +
	"\n" +
	"GetMyTrips\x12\x1b.rider.GetRiderTripsRequest\x1a\x1c.rider.GetRiderTripsResponseB%Z#github.com/taxxy/shared/proto/riderb\x06proto3"

var (
	file_proto_rider_rider_proto_rawDescOnce sync.Once
	file_proto_rider_rider_proto_rawDescData []byte
)

func file_proto_rider_rider_proto_rawDescGZIP() []byte {
	file_proto_rider_rider_proto_rawDescOnce.Do(func() {
		file_proto_rider_rider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rider_rider_proto_rawDesc), len(file_proto_rider_rider_proto_rawDesc)))
	})
	return file_proto_rider_rider_proto_rawDescData
}

var file_proto_rider_rider_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_rider_rider_proto_goTypes = []any{
	(*CreateRiderProfileRequest)(nil),  // 0: rider.CreateRiderProfileRequest
	(*CreateRiderProfileResponse)(nil), // 1: rider.CreateRiderProfileResponse
	(*GetRiderProfileRequest)(nil),     // 2: rider.GetRiderProfileRequest
	(*RiderProfile)(nil),               // 3: rider.RiderProfile
	(*RequestRideRequest)(nil),         // 4: rider.RequestRideRequest
	(*RequestRideResponse)(nil),        // 5: rider.RequestRideResponse
	(*GetRiderTripsRequest)(nil),       // 6: rider.GetRiderTripsRequest
	(*GetRiderTripsResponse)(nil),      // 7: rider.GetRiderTripsResponse
	(*RiderTripSummary)(nil),           // 8: rider.RiderTripSummary
	(*shared.Location)(nil),            // 9: shared.Location
}
var file_proto_rider_rider_proto_depIdxs = []int32{
	9, // 0: rider.RequestRideRequest.pickup:type_name -> shared.Location
	9, // 1: rider.RequestRideRequest.dropoff:type_name -> shared.Location
	8, // 2: rider.GetRiderTripsResponse.trips:type_name -> rider.RiderTripSummary
	0, // 3: rider.RiderService.CreateProfile:input_type -> rider.CreateRiderProfileRequest
	2, // 4: rider.RiderService.GetProfile:input_type -> rider.GetRiderProfileRequest
	4, // 5: rider.RiderService.RequestRide:input_type -> rider.RequestRideRequest
	6, // 6: rider.RiderService.GetMyTrips:input_type -> rider.GetRiderTripsRequest
	1, // 7: rider.RiderService.CreateProfile:output_type -> rider.CreateRiderProfileResponse
	3, // 8: rider.RiderService.GetProfile:output_type -> rider.RiderProfile
	5, // 9: rider.RiderService.RequestRide:output_type -> rider.RequestRideResponse
	7, // 10: rider.RiderService.GetMyTrips:output_type -> rider.GetRiderTripsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_rider_rider_proto_init() }
func file_proto_rider_rider_proto_init() {
	if File_proto_rider_rider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rider_rider_proto_rawDesc), len(file_proto_rider_rider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rider_rider_proto_goTypes,
		DependencyIndexes: file_proto_rider_rider_proto_depIdxs,
		MessageInfos:      file_proto_rider_rider_proto_msgTypes,
	}.Build()
	File_proto_rider_rider_proto = out.File
	file_proto_rider_rider_proto_goTypes = nil
	file_proto_rider_rider_proto_depIdxs = nil
}
