// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/driver/driver.proto

package driver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriverService_CreateProfile_FullMethodName      = "/driver.DriverService/CreateProfile"
	DriverService_GetProfile_FullMethodName         = "/driver.DriverService/GetProfile"
	DriverService_UpdateAvailability_FullMethodName = "/driver.DriverService/UpdateAvailability"
	DriverService_AcceptRide_FullMethodName         = "/driver.DriverService/AcceptRide"
	DriverService_CompleteRide_FullMethodName       = "/driver.DriverService/CompleteRide"
	DriverService_GetMyTrips_FullMethodName         = "/driver.DriverService/GetMyTrips"
)

// DriverServiceClient is the client API for DriverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverServiceClient interface {
	CreateProfile(ctx context.Context, in *CreateDriverProfileRequest, opts ...grpc.CallOption) (*CreateDriverProfileResponse, error)
	GetProfile(ctx context.Context, in *GetDriverProfileRequest, opts ...grpc.CallOption) (*DriverProfile, error)
	UpdateAvailability(ctx context.Context, in *UpdateAvailabilityRequest, opts ...grpc.CallOption) (*UpdateAvailabilityResponse, error)
	AcceptRide(ctx context.Context, in *AcceptRideRequest, opts ...grpc.CallOption) (*AcceptRideResponse, error)
	CompleteRide(ctx context.Context, in *CompleteRideRequest, opts ...grpc.CallOption) (*CompleteRideResponse, error)
	GetMyTrips(ctx context.Context, in *GetDriverTripsRequest, opts ...grpc.CallOption) (*GetDriverTripsResponse, error)
}

type driverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverServiceClient(cc grpc.ClientConnInterface) DriverServiceClient {
	return &driverServiceClient{cc}
}

func (c *driverServiceClient) CreateProfile(ctx context.Context, in *CreateDriverProfileRequest, opts ...grpc.CallOption) (*CreateDriverProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDriverProfileResponse)
	err := c.cc.Invoke(ctx, DriverService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetProfile(ctx context.Context, in *GetDriverProfileRequest, opts ...grpc.CallOption) (*DriverProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverProfile)
	err := c.cc.Invoke(ctx, DriverService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateAvailability(ctx context.Context, in *UpdateAvailabilityRequest, opts ...grpc.CallOption) (*UpdateAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAvailabilityResponse)
	err := c.cc.Invoke(ctx, DriverService_UpdateAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) AcceptRide(ctx context.Context, in *AcceptRideRequest, opts ...grpc.CallOption) (*AcceptRideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptRideResponse)
	err := c.cc.Invoke(ctx, DriverService_AcceptRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) CompleteRide(ctx context.Context, in *CompleteRideRequest, opts ...grpc.CallOption) (*CompleteRideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteRideResponse)
	err := c.cc.Invoke(ctx, DriverService_CompleteRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetMyTrips(ctx context.Context, in *GetDriverTripsRequest, opts ...grpc.CallOption) (*GetDriverTripsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverTripsResponse)
	err := c.cc.Invoke(ctx, DriverService_GetMyTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServiceServer is the server API for DriverService service.
// All implementations must embed UnimplementedDriverServiceServer
// for forward compatibility.
type DriverServiceServer interface {
	CreateProfile(context.Context, *CreateDriverProfileRequest) (*CreateDriverProfileResponse, error)
	GetProfile(context.Context, *GetDriverProfileRequest) (*DriverProfile, error)
	UpdateAvailability(context.Context, *UpdateAvailabilityRequest) (*UpdateAvailabilityResponse, error)
	AcceptRide(context.Context, *AcceptRideRequest) (*AcceptRideResponse, error)
	CompleteRide(context.Context, *CompleteRideRequest) (*CompleteRideResponse, error)
	GetMyTrips(context.Context, *GetDriverTripsRequest) (*GetDriverTripsResponse, error)
	mustEmbedUnimplementedDriverServiceServer()
}

// UnimplementedDriverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServiceServer struct{}

func (UnimplementedDriverServiceServer) CreateProfile(context.Context, *CreateDriverProfileRequest) (*CreateDriverProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedDriverServiceServer) GetProfile(context.Context, *GetDriverProfileRequest) (*DriverProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedDriverServiceServer) UpdateAvailability(context.Context, *UpdateAvailabilityRequest) (*UpdateAvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAvailability not implemented")
}
func (UnimplementedDriverServiceServer) AcceptRide(context.Context, *AcceptRideRequest) (*AcceptRideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptRide not implemented")
}
func (UnimplementedDriverServiceServer) CompleteRide(context.Context, *CompleteRideRequest) (*CompleteRideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteRide not implemented")
}
func (UnimplementedDriverServiceServer) GetMyTrips(context.Context, *GetDriverTripsRequest) (*GetDriverTripsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyTrips not implemented")
}
func (UnimplementedDriverServiceServer) mustEmbedUnimplementedDriverServiceServer() {}
func (UnimplementedDriverServiceServer) testEmbeddedByValue()                       {}

// UnsafeDriverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServiceServer will
// result in compilation errors.
type UnsafeDriverServiceServer interface {
	mustEmbedUnimplementedDriverServiceServer()
}

func RegisterDriverServiceServer(s grpc.ServiceRegistrar, srv DriverServiceServer) {
	// If the following call panics, it indicates UnimplementedDriverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverService_ServiceDesc, srv)
}

func _DriverService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDriverProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).CreateProfile(ctx, req.(*CreateDriverProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetProfile(ctx, req.(*GetDriverProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateAvailability(ctx, req.(*UpdateAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_AcceptRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).AcceptRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_AcceptRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).AcceptRide(ctx, req.(*AcceptRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_CompleteRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).CompleteRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_CompleteRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).CompleteRide(ctx, req.(*CompleteRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetMyTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetMyTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetMyTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetMyTrips(ctx, req.(*GetDriverTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverService_ServiceDesc is the grpc.ServiceDesc for DriverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.DriverService",
	HandlerType: (*DriverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfile",
			Handler:    _DriverService_CreateProfile_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _DriverService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateAvailability",
			Handler:    _DriverService_UpdateAvailability_Handler,
		},
		{
			MethodName: "AcceptRide",
			Handler:    _DriverService_AcceptRide_Handler,
		},
		{
			MethodName: "CompleteRide",
			Handler:    _DriverService_CompleteRide_Handler,
		},
		{
			MethodName: "GetMyTrips",
			Handler:    _DriverService_GetMyTrips_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/driver/driver.proto",
}
