// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/driver/driver_test.proto

package driver

import (
	shared "github.com/taxxy/shared/proto/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDriverProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	VehicleType   string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,5,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	VehicleBrand  string                 `protobuf:"bytes,6,opt,name=vehicle_brand,json=vehicleBrand,proto3" json:"vehicle_brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverProfileRequest) Reset() {
	*x = CreateDriverProfileRequest{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverProfileRequest) ProtoMessage() {}

func (x *CreateDriverProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateDriverProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDriverProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateDriverProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDriverProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateDriverProfileRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CreateDriverProfileRequest) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *CreateDriverProfileRequest) GetVehicleBrand() string {
	if x != nil {
		return x.VehicleBrand
	}
	return ""
}

type CreateDriverProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverProfileResponse) Reset() {
	*x = CreateDriverProfileResponse{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverProfileResponse) ProtoMessage() {}

func (x *CreateDriverProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateDriverProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDriverProfileResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CreateDriverProfileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetDriverProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverProfileRequest) Reset() {
	*x = GetDriverProfileRequest{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverProfileRequest) ProtoMessage() {}

func (x *GetDriverProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverProfileRequest.ProtoReflect.Descriptor instead.
func (*GetDriverProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{2}
}

func (x *GetDriverProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DriverProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	VehicleType   string                 `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,6,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	VehicleBrand  string                 `protobuf:"bytes,7,opt,name=vehicle_brand,json=vehicleBrand,proto3" json:"vehicle_brand,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // available, busy, offline
	AverageRating float64                `protobuf:"fixed64,9,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	CurrentLat    float64                `protobuf:"fixed64,10,opt,name=current_lat,json=currentLat,proto3" json:"current_lat,omitempty"`
	CurrentLng    float64                `protobuf:"fixed64,11,opt,name=current_lng,json=currentLng,proto3" json:"current_lng,omitempty"`
	TotalTrips    int32                  `protobuf:"varint,12,opt,name=total_trips,json=totalTrips,proto3" json:"total_trips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverProfile) Reset() {
	*x = DriverProfile{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverProfile) ProtoMessage() {}

func (x *DriverProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverProfile.ProtoReflect.Descriptor instead.
func (*DriverProfile) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{3}
}

func (x *DriverProfile) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DriverProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DriverProfile) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *DriverProfile) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *DriverProfile) GetVehicleBrand() string {
	if x != nil {
		return x.VehicleBrand
	}
	return ""
}

func (x *DriverProfile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverProfile) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *DriverProfile) GetCurrentLat() float64 {
	if x != nil {
		return x.CurrentLat
	}
	return 0
}

func (x *DriverProfile) GetCurrentLng() float64 {
	if x != nil {
		return x.CurrentLng
	}
	return 0
}

func (x *DriverProfile) GetTotalTrips() int32 {
	if x != nil {
		return x.TotalTrips
	}
	return 0
}

type UpdateAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Location      *shared.Location       `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvailabilityRequest) Reset() {
	*x = UpdateAvailabilityRequest{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvailabilityRequest) ProtoMessage() {}

func (x *UpdateAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAvailabilityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateAvailabilityRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateAvailabilityRequest) GetLocation() *shared.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvailabilityResponse) Reset() {
	*x = UpdateAvailabilityResponse{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvailabilityResponse) ProtoMessage() {}

func (x *UpdateAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*UpdateAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAvailabilityResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AcceptRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRideRequest) Reset() {
	*x = AcceptRideRequest{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRideRequest) ProtoMessage() {}

func (x *AcceptRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRideRequest.ProtoReflect.Descriptor instead.
func (*AcceptRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptRideRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcceptRideRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type AcceptRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRideResponse) Reset() {
	*x = AcceptRideResponse{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRideResponse) ProtoMessage() {}

func (x *AcceptRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRideResponse.ProtoReflect.Descriptor instead.
func (*AcceptRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptRideResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *AcceptRideResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CompleteRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRideRequest) Reset() {
	*x = CompleteRideRequest{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRideRequest) ProtoMessage() {}

func (x *CompleteRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRideRequest.ProtoReflect.Descriptor instead.
func (*CompleteRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteRideRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteRideRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type CompleteRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Fare          float64                `protobuf:"fixed64,3,opt,name=fare,proto3" json:"fare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRideResponse) Reset() {
	*x = CompleteRideResponse{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRideResponse) ProtoMessage() {}

func (x *CompleteRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRideResponse.ProtoReflect.Descriptor instead.
func (*CompleteRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteRideResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CompleteRideResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CompleteRideResponse) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

type GetDriverTripsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverTripsRequest) Reset() {
	*x = GetDriverTripsRequest{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverTripsRequest) ProtoMessage() {}

func (x *GetDriverTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverTripsRequest.ProtoReflect.Descriptor instead.
func (*GetDriverTripsRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{10}
}

func (x *GetDriverTripsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDriverTripsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDriverTripsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetDriverTripsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trips         []*DriverTripSummary   `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverTripsResponse) Reset() {
	*x = GetDriverTripsResponse{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverTripsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverTripsResponse) ProtoMessage() {}

func (x *GetDriverTripsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverTripsResponse.ProtoReflect.Descriptor instead.
func (*GetDriverTripsResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{11}
}

func (x *GetDriverTripsResponse) GetTrips() []*DriverTripSummary {
	if x != nil {
		return x.Trips
	}
	return nil
}

func (x *GetDriverTripsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DriverTripSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Fare          float64                `protobuf:"fixed64,3,opt,name=fare,proto3" json:"fare,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverTripSummary) Reset() {
	*x = DriverTripSummary{}
	mi := &file_proto_driver_driver_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverTripSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverTripSummary) ProtoMessage() {}

func (x *DriverTripSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverTripSummary.ProtoReflect.Descriptor instead.
func (*DriverTripSummary) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_test_proto_rawDescGZIP(), []int{12}
}

func (x *DriverTripSummary) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *DriverTripSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverTripSummary) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

func (x *DriverTripSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_driver_driver_test_proto protoreflect.FileDescriptor

const file_proto_driver_driver_test_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/driver/driver_test.proto\x12\x06driver\x1a\x19proto/shared/shared.proto\"\xcc\x01\n" +
	"\x1aCreateDriverProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\x12#\n" +
	"\rvehicle_plate\x18\x05 \x01(\tR\fvehiclePlate\x12#\n" +
	"\rvehicle_brand\x18\x06 \x01(\tR\fvehicleBrand\"R\n" +
	"\x1bCreateDriverProfileResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"2\n" +
	"\x17GetDriverProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xfe\x02\n" +
	"\rDriverProfile\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12!\n" +
	"\fvehicle_type\x18\x05 \x01(\tR\vvehicleType\x12#\n" +
	"\rvehicle_plate\x18\x06 \x01(\tR\fvehiclePlate\x12#\n" +
	"\rvehicle_brand\x18\a \x01(\tR\fvehicleBrand\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0eaverage_rating\x18\t \x01(\x01R\raverageRating\x12\x1f\n" +
	"\vcurrent_lat\x18\n" +
	" \x01(\x01R\n" +
	"currentLat\x12\x1f\n" +
	"\vcurrent_lng\x18\v \x01(\x01R\n" +
	"currentLng\x12\x1f\n" +
	"\vtotal_trips\x18\f \x01(\x05R\n" +
	"totalTrips\"z\n" +
	"\x19UpdateAvailabilityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\blocation\x18\x03 \x01(\v2\x10.shared.LocationR\blocation\"4\n" +
	"\x1aUpdateAvailabilityResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"E\n" +
	"\x11AcceptRideRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\"E\n" +
	"\x12AcceptRideResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"G\n" +
	"\x13CompleteRideRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\"[\n" +
	"\x14CompleteRideResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04fare\x18\x03 \x01(\x01R\x04fare\"^\n" +
	"\x15GetDriverTripsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"_\n" +
	"\x16GetDriverTripsResponse\x12/\n" +
	"\x05trips\x18\x01 \x03(\v2\x19.driver.DriverTripSummaryR\x05trips\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"w\n" +
	"\x11DriverTripSummary\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04fare\x18\x03 \x01(\x01R\x04fare\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt2\xe9\x03\n" +
	"\rDriverService\x12X\n" +
	"\rCreateProfile\x12\".driver.CreateDriverProfileRequest\x1a#.driver.CreateDriverProfileResponse\x12D\n" +
	"\n" +
	"GetProfile\x12\x1f.driver.GetDriverProfileRequest\x1a\x15.driver.DriverProfile\x12[\n" +
	"\x12UpdateAvailability\x12!.driver.UpdateAvailabilityRequest\x1a\".driver.UpdateAvailabilityResponse\x12C\n" +
	"\n" +
	"AcceptRide\x12\x19.driver.AcceptRideRequest\x1a\x1a.driver.AcceptRideResponse\x12I\n" +
	"\fCompleteRide\x12\x1b.driver.CompleteRideRequest\x1a\x1c.driver.CompleteRideResponse\x12K\n" +
	"\n" +
	"GetMyTrips\x12\x1d.driver.GetDriverTripsRequest\x1a\x1e.driver.GetDriverTripsResponseB&Z$github.com/taxxy/shared/proto/driverb\x06proto3"

var (
	file_proto_driver_driver_test_proto_rawDescOnce sync.Once
	file_proto_driver_driver_test_proto_rawDescData []byte
)

func file_proto_driver_driver_test_proto_rawDescGZIP() []byte {
	file_proto_driver_driver_test_proto_rawDescOnce.Do(func() {
		file_proto_driver_driver_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driver_driver_test_proto_rawDesc), len(file_proto_driver_driver_test_proto_rawDesc)))
	})
	return file_proto_driver_driver_test_proto_rawDescData
}

var file_proto_driver_driver_test_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_driver_driver_test_proto_goTypes = []any{
	(*CreateDriverProfileRequest)(nil),  // 0: driver.CreateDriverProfileRequest
	(*CreateDriverProfileResponse)(nil), // 1: driver.CreateDriverProfileResponse
	(*GetDriverProfileRequest)(nil),     // 2: driver.GetDriverProfileRequest
	(*DriverProfile)(nil),               // 3: driver.DriverProfile
	(*UpdateAvailabilityRequest)(nil),   // 4: driver.UpdateAvailabilityRequest
	(*UpdateAvailabilityResponse)(nil),  // 5: driver.UpdateAvailabilityResponse
	(*AcceptRideRequest)(nil),           // 6: driver.AcceptRideRequest
	(*AcceptRideResponse)(nil),          // 7: driver.AcceptRideResponse
	(*CompleteRideRequest)(nil),         // 8: driver.CompleteRideRequest
	(*CompleteRideResponse)(nil),        // 9: driver.CompleteRideResponse
	(*GetDriverTripsRequest)(nil),       // 10: driver.GetDriverTripsRequest
	(*GetDriverTripsResponse)(nil),      // 11: driver.GetDriverTripsResponse
	(*DriverTripSummary)(nil),           // 12: driver.DriverTripSummary
	(*shared.Location)(nil),             // 13: shared.Location
}
var file_proto_driver_driver_test_proto_depIdxs = []int32{
	13, // 0: driver.UpdateAvailabilityRequest.location:type_name -> shared.Location
	12, // 1: driver.GetDriverTripsResponse.trips:type_name -> driver.DriverTripSummary
	0,  // 2: driver.DriverService.CreateProfile:input_type -> driver.CreateDriverProfileRequest
	2,  // 3: driver.DriverService.GetProfile:input_type -> driver.GetDriverProfileRequest
	4,  // 4: driver.DriverService.UpdateAvailability:input_type -> driver.UpdateAvailabilityRequest
	6,  // 5: driver.DriverService.AcceptRide:input_type -> driver.AcceptRideRequest
	8,  // 6: driver.DriverService.CompleteRide:input_type -> driver.CompleteRideRequest
	10, // 7: driver.DriverService.GetMyTrips:input_type -> driver.GetDriverTripsRequest
	1,  // 8: driver.DriverService.CreateProfile:output_type -> driver.CreateDriverProfileResponse
	3,  // 9: driver.DriverService.GetProfile:output_type -> driver.DriverProfile
	5,  // 10: driver.DriverService.UpdateAvailability:output_type -> driver.UpdateAvailabilityResponse
	7,  // 11: driver.DriverService.AcceptRide:output_type -> driver.AcceptRideResponse
	9,  // 12: driver.DriverService.CompleteRide:output_type -> driver.CompleteRideResponse
	11, // 13: driver.DriverService.GetMyTrips:output_type -> driver.GetDriverTripsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_driver_driver_test_proto_init() }
func file_proto_driver_driver_test_proto_init() {
	if File_proto_driver_driver_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driver_driver_test_proto_rawDesc), len(file_proto_driver_driver_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driver_driver_test_proto_goTypes,
		DependencyIndexes: file_proto_driver_driver_test_proto_depIdxs,
		MessageInfos:      file_proto_driver_driver_test_proto_msgTypes,
	}.Build()
	File_proto_driver_driver_test_proto = out.File
	file_proto_driver_driver_test_proto_goTypes = nil
	file_proto_driver_driver_test_proto_depIdxs = nil
}
