// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/trip/trip.proto

package trip

import (
	shared "github.com/taxxy/shared/proto/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Pickup        *shared.Location       `protobuf:"bytes,2,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *shared.Location       `protobuf:"bytes,3,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	VehicleType   string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	EstimatedFare float64                `protobuf:"fixed64,5,opt,name=estimated_fare,json=estimatedFare,proto3" json:"estimated_fare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_proto_trip_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTripRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *CreateTripRequest) GetPickup() *shared.Location {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *CreateTripRequest) GetDropoff() *shared.Location {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *CreateTripRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CreateTripRequest) GetEstimatedFare() float64 {
	if x != nil {
		return x.EstimatedFare
	}
	return 0
}

type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	EstimatedFare float64                `protobuf:"fixed64,2,opt,name=estimated_fare,json=estimatedFare,proto3" json:"estimated_fare,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_proto_trip_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CreateTripResponse) GetEstimatedFare() float64 {
	if x != nil {
		return x.EstimatedFare
	}
	return 0
}

func (x *CreateTripResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripRequest) Reset() {
	*x = GetTripRequest{}
	mi := &file_proto_trip_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripRequest) ProtoMessage() {}

func (x *GetTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripRequest.ProtoReflect.Descriptor instead.
func (*GetTripRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{2}
}

func (x *GetTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type TripDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Pickup        *shared.Location       `protobuf:"bytes,5,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *shared.Location       `protobuf:"bytes,6,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	EstimatedFare float64                `protobuf:"fixed64,7,opt,name=estimated_fare,json=estimatedFare,proto3" json:"estimated_fare,omitempty"`
	FinalFare     float64                `protobuf:"fixed64,8,opt,name=final_fare,json=finalFare,proto3" json:"final_fare,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,9,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	DurationSec   int64                  `protobuf:"varint,10,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	VehicleType   string                 `protobuf:"bytes,13,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripDetails) Reset() {
	*x = TripDetails{}
	mi := &file_proto_trip_trip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripDetails) ProtoMessage() {}

func (x *TripDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripDetails.ProtoReflect.Descriptor instead.
func (*TripDetails) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{3}
}

func (x *TripDetails) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripDetails) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *TripDetails) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *TripDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TripDetails) GetPickup() *shared.Location {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *TripDetails) GetDropoff() *shared.Location {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *TripDetails) GetEstimatedFare() float64 {
	if x != nil {
		return x.EstimatedFare
	}
	return 0
}

func (x *TripDetails) GetFinalFare() float64 {
	if x != nil {
		return x.FinalFare
	}
	return 0
}

func (x *TripDetails) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *TripDetails) GetDurationSec() int64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *TripDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TripDetails) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TripDetails) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

type AssignDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverRequest) Reset() {
	*x = AssignDriverRequest{}
	mi := &file_proto_trip_trip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverRequest) ProtoMessage() {}

func (x *AssignDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverRequest.ProtoReflect.Descriptor instead.
func (*AssignDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{4}
}

func (x *AssignDriverRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *AssignDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type AssignDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDriverResponse) Reset() {
	*x = AssignDriverResponse{}
	mi := &file_proto_trip_trip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDriverResponse) ProtoMessage() {}

func (x *AssignDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDriverResponse.ProtoReflect.Descriptor instead.
func (*AssignDriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{5}
}

func (x *AssignDriverResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *AssignDriverResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateTripStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTripStatusRequest) Reset() {
	*x = UpdateTripStatusRequest{}
	mi := &file_proto_trip_trip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTripStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripStatusRequest) ProtoMessage() {}

func (x *UpdateTripStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTripStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTripStatusRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *UpdateTripStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateTripStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FinalFare     float64                `protobuf:"fixed64,3,opt,name=final_fare,json=finalFare,proto3" json:"final_fare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTripStatusResponse) Reset() {
	*x = UpdateTripStatusResponse{}
	mi := &file_proto_trip_trip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTripStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripStatusResponse) ProtoMessage() {}

func (x *UpdateTripStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTripStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTripStatusResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *UpdateTripStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTripStatusResponse) GetFinalFare() float64 {
	if x != nil {
		return x.FinalFare
	}
	return 0
}

type ListTripsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTripsRequest) Reset() {
	*x = ListTripsRequest{}
	mi := &file_proto_trip_trip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTripsRequest) ProtoMessage() {}

func (x *ListTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTripsRequest.ProtoReflect.Descriptor instead.
func (*ListTripsRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{8}
}

func (x *ListTripsRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *ListTripsRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ListTripsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTripsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTripsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTripsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trips         []*TripDetails         `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTripsResponse) Reset() {
	*x = ListTripsResponse{}
	mi := &file_proto_trip_trip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTripsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTripsResponse) ProtoMessage() {}

func (x *ListTripsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTripsResponse.ProtoReflect.Descriptor instead.
func (*ListTripsResponse) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{9}
}

func (x *ListTripsResponse) GetTrips() []*TripDetails {
	if x != nil {
		return x.Trips
	}
	return nil
}

func (x *ListTripsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_trip_trip_proto protoreflect.FileDescriptor

const file_proto_trip_trip_proto_rawDesc = "" +
	"\n" +
	"\x15proto/trip/trip.proto\x12\x04trip\x1a\x19proto/shared/shared.proto\"\xce\x01\n" +
	"\x11CreateTripRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12(\n" +
	"\x06pickup\x18\x02 \x01(\v2\x10.shared.LocationR\x06pickup\x12*\n" +
	"\adropoff\x18\x03 \x01(\v2\x10.shared.LocationR\adropoff\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\x12%\n" +
	"\x0eestimated_fare\x18\x05 \x01(\x01R\restimatedFare\"l\n" +
	"\x12CreateTripResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12%\n" +
	"\x0eestimated_fare\x18\x02 \x01(\x01R\restimatedFare\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\")\n" +
	"\x0eGetTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"\xb7\x03\n" +
	"\vTripDetails\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12(\n" +
	"\x06pickup\x18\x05 \x01(\v2\x10.shared.LocationR\x06pickup\x12*\n" +
	"\adropoff\x18\x06 \x01(\v2\x10.shared.LocationR\adropoff\x12%\n" +
	"\x0eestimated_fare\x18\a \x01(\x01R\restimatedFare\x12\x1d\n" +
	"\n" +
	"final_fare\x18\b \x01(\x01R\tfinalFare\x12\x1f\n" +
	"\vdistance_km\x18\t \x01(\x01R\n" +
	"distanceKm\x12!\n" +
	"\fduration_sec\x18\n" +
	" \x01(\x03R\vdurationSec\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12!\n" +
	"\fvehicle_type\x18\r \x01(\tR\vvehicleType\"K\n" +
	"\x13AssignDriverRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"G\n" +
	"\x14AssignDriverResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"J\n" +
	"\x17UpdateTripStatusRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"j\n" +
	"\x18UpdateTripStatusResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"final_fare\x18\x03 \x01(\x01R\tfinalFare\"\x90\x01\n" +
	"\x10ListTripsRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"R\n" +
	"\x11ListTripsResponse\x12'\n" +
	"\x05trips\x18\x01 \x03(\v2\x11.trip.TripDetailsR\x05trips\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xda\x02\n" +
	"\vTripService\x12?\n" +
	"\n" +
	"CreateTrip\x12\x17.trip.CreateTripRequest\x1a\x18.trip.CreateTripResponse\x122\n" +
	"\aGetTrip\x12\x14.trip.GetTripRequest\x1a\x11.trip.TripDetails\x12E\n" +
	"\fAssignDriver\x12\x19.trip.AssignDriverRequest\x1a\x1a.trip.AssignDriverResponse\x12Q\n" +
	"\x10UpdateTripStatus\x12\x1d.trip.UpdateTripStatusRequest\x1a\x1e.trip.UpdateTripStatusResponse\x12<\n" +
	"\tListTrips\x12\x16.trip.ListTripsRequest\x1a\x17.trip.ListTripsResponseB$Z\"github.com/taxxy/shared/proto/tripb\x06proto3"

var (
	file_proto_trip_trip_proto_rawDescOnce sync.Once
	file_proto_trip_trip_proto_rawDescData []byte
)

func file_proto_trip_trip_proto_rawDescGZIP() []byte {
	file_proto_trip_trip_proto_rawDescOnce.Do(func() {
		file_proto_trip_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trip_trip_proto_rawDesc), len(file_proto_trip_trip_proto_rawDesc)))
	})
	return file_proto_trip_trip_proto_rawDescData
}

var file_proto_trip_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_trip_trip_proto_goTypes = []any{
	(*CreateTripRequest)(nil),        // 0: trip.CreateTripRequest
	(*CreateTripResponse)(nil),       // 1: trip.CreateTripResponse
	(*GetTripRequest)(nil),           // 2: trip.GetTripRequest
	(*TripDetails)(nil),              // 3: trip.TripDetails
	(*AssignDriverRequest)(nil),      // 4: trip.AssignDriverRequest
	(*AssignDriverResponse)(nil),     // 5: trip.AssignDriverResponse
	(*UpdateTripStatusRequest)(nil),  // 6: trip.UpdateTripStatusRequest
	(*UpdateTripStatusResponse)(nil), // 7: trip.UpdateTripStatusResponse
	(*ListTripsRequest)(nil),         // 8: trip.ListTripsRequest
	(*ListTripsResponse)(nil),        // 9: trip.ListTripsResponse
	(*shared.Location)(nil),          // 10: shared.Location
}
var file_proto_trip_trip_proto_depIdxs = []int32{
	10, // 0: trip.CreateTripRequest.pickup:type_name -> shared.Location
	10, // 1: trip.CreateTripRequest.dropoff:type_name -> shared.Location
	10, // 2: trip.TripDetails.pickup:type_name -> shared.Location
	10, // 3: trip.TripDetails.dropoff:type_name -> shared.Location
	3,  // 4: trip.ListTripsResponse.trips:type_name -> trip.TripDetails
	0,  // 5: trip.TripService.CreateTrip:input_type -> trip.CreateTripRequest
	2,  // 6: trip.TripService.GetTrip:input_type -> trip.GetTripRequest
	4,  // 7: trip.TripService.AssignDriver:input_type -> trip.AssignDriverRequest
	6,  // 8: trip.TripService.UpdateTripStatus:input_type -> trip.UpdateTripStatusRequest
	8,  // 9: trip.TripService.ListTrips:input_type -> trip.ListTripsRequest
	1,  // 10: trip.TripService.CreateTrip:output_type -> trip.CreateTripResponse
	3,  // 11: trip.TripService.GetTrip:output_type -> trip.TripDetails
	5,  // 12: trip.TripService.AssignDriver:output_type -> trip.AssignDriverResponse
	7,  // 13: trip.TripService.UpdateTripStatus:output_type -> trip.UpdateTripStatusResponse
	9,  // 14: trip.TripService.ListTrips:output_type -> trip.ListTripsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_trip_trip_proto_init() }
func file_proto_trip_trip_proto_init() {
	if File_proto_trip_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trip_trip_proto_rawDesc), len(file_proto_trip_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trip_trip_proto_goTypes,
		DependencyIndexes: file_proto_trip_trip_proto_depIdxs,
		MessageInfos:      file_proto_trip_trip_proto_msgTypes,
	}.Build()
	File_proto_trip_trip_proto = out.File
	file_proto_trip_trip_proto_goTypes = nil
	file_proto_trip_trip_proto_depIdxs = nil
}
