// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateFareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PickupLat     float64                `protobuf:"fixed64,1,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLng     float64                `protobuf:"fixed64,2,opt,name=pickup_lng,json=pickupLng,proto3" json:"pickup_lng,omitempty"`
	DropoffLat    float64                `protobuf:"fixed64,3,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLng    float64                `protobuf:"fixed64,4,opt,name=dropoff_lng,json=dropoffLng,proto3" json:"dropoff_lng,omitempty"`
	VehicleType   string                 `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateFareRequest) Reset() {
	*x = CalculateFareRequest{}
	mi := &file_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFareRequest) ProtoMessage() {}

func (x *CalculateFareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFareRequest.ProtoReflect.Descriptor instead.
func (*CalculateFareRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateFareRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *CalculateFareRequest) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *CalculateFareRequest) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *CalculateFareRequest) GetDropoffLng() float64 {
	if x != nil {
		return x.DropoffLng
	}
	return 0
}

func (x *CalculateFareRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

type CalculateFareResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseFare        float64                `protobuf:"fixed64,1,opt,name=base_fare,json=baseFare,proto3" json:"base_fare,omitempty"`
	DistanceKm      float64                `protobuf:"fixed64,2,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	DurationMin     float64                `protobuf:"fixed64,3,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	SurgeMultiplier float64                `protobuf:"fixed64,4,opt,name=surge_multiplier,json=surgeMultiplier,proto3" json:"surge_multiplier,omitempty"`
	TotalFare       float64                `protobuf:"fixed64,5,opt,name=total_fare,json=totalFare,proto3" json:"total_fare,omitempty"`
	Breakdown       string                 `protobuf:"bytes,6,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateFareResponse) Reset() {
	*x = CalculateFareResponse{}
	mi := &file_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFareResponse) ProtoMessage() {}

func (x *CalculateFareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFareResponse.ProtoReflect.Descriptor instead.
func (*CalculateFareResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateFareResponse) GetBaseFare() float64 {
	if x != nil {
		return x.BaseFare
	}
	return 0
}

func (x *CalculateFareResponse) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *CalculateFareResponse) GetDurationMin() float64 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *CalculateFareResponse) GetSurgeMultiplier() float64 {
	if x != nil {
		return x.SurgeMultiplier
	}
	return 0
}

func (x *CalculateFareResponse) GetTotalFare() float64 {
	if x != nil {
		return x.TotalFare
	}
	return 0
}

func (x *CalculateFareResponse) GetBreakdown() string {
	if x != nil {
		return x.Breakdown
	}
	return ""
}

type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessPaymentRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessPaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessPaymentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type PaymentDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,3,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentDetails) Reset() {
	*x = PaymentDetails{}
	mi := &file_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDetails) ProtoMessage() {}

func (x *PaymentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDetails.ProtoReflect.Descriptor instead.
func (*PaymentDetails) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentDetails) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentDetails) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *PaymentDetails) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *PaymentDetails) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentDetails) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaymentDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentDetails) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *RefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *RefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *RefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefundResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetDriverEarningsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverEarningsRequest) Reset() {
	*x = GetDriverEarningsRequest{}
	mi := &file_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverEarningsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverEarningsRequest) ProtoMessage() {}

func (x *GetDriverEarningsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverEarningsRequest.ProtoReflect.Descriptor instead.
func (*GetDriverEarningsRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetDriverEarningsRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverEarningsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetDriverEarningsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type DriverEarnings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DriverId       string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TotalEarned    float64                `protobuf:"fixed64,2,opt,name=total_earned,json=totalEarned,proto3" json:"total_earned,omitempty"`
	TotalTrips     int32                  `protobuf:"varint,3,opt,name=total_trips,json=totalTrips,proto3" json:"total_trips,omitempty"`
	AveragePerTrip float64                `protobuf:"fixed64,4,opt,name=average_per_trip,json=averagePerTrip,proto3" json:"average_per_trip,omitempty"`
	PeriodFrom     string                 `protobuf:"bytes,5,opt,name=period_from,json=periodFrom,proto3" json:"period_from,omitempty"`
	PeriodTo       string                 `protobuf:"bytes,6,opt,name=period_to,json=periodTo,proto3" json:"period_to,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DriverEarnings) Reset() {
	*x = DriverEarnings{}
	mi := &file_payment_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverEarnings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverEarnings) ProtoMessage() {}

func (x *DriverEarnings) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverEarnings.ProtoReflect.Descriptor instead.
func (*DriverEarnings) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{9}
}

func (x *DriverEarnings) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverEarnings) GetTotalEarned() float64 {
	if x != nil {
		return x.TotalEarned
	}
	return 0
}

func (x *DriverEarnings) GetTotalTrips() int32 {
	if x != nil {
		return x.TotalTrips
	}
	return 0
}

func (x *DriverEarnings) GetAveragePerTrip() float64 {
	if x != nil {
		return x.AveragePerTrip
	}
	return 0
}

func (x *DriverEarnings) GetPeriodFrom() string {
	if x != nil {
		return x.PeriodFrom
	}
	return ""
}

func (x *DriverEarnings) GetPeriodTo() string {
	if x != nil {
		return x.PeriodTo
	}
	return ""
}

var File_payment_payment_proto protoreflect.FileDescriptor

const file_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x15payment/payment.proto\x12\apayment\"\xb9\x01\n" +
	"\x14CalculateFareRequest\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x01 \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lng\x18\x02 \x01(\x01R\tpickupLng\x12\x1f\n" +
	"\vdropoff_lat\x18\x03 \x01(\x01R\n" +
	"dropoffLat\x12\x1f\n" +
	"\vdropoff_lng\x18\x04 \x01(\x01R\n" +
	"dropoffLng\x12!\n" +
	"\fvehicle_type\x18\x05 \x01(\tR\vvehicleType\"\xe0\x01\n" +
	"\x15CalculateFareResponse\x12\x1b\n" +
	"\tbase_fare\x18\x01 \x01(\x01R\bbaseFare\x12\x1f\n" +
	"\vdistance_km\x18\x02 \x01(\x01R\n" +
	"distanceKm\x12!\n" +
	"\fduration_min\x18\x03 \x01(\x01R\vdurationMin\x12)\n" +
	"\x10surge_multiplier\x18\x04 \x01(\x01R\x0fsurgeMultiplier\x12\x1d\n" +
	"\n" +
	"total_fare\x18\x05 \x01(\x01R\ttotalFare\x12\x1c\n" +
	"\tbreakdown\x18\x06 \x01(\tR\tbreakdown\"\x8a\x01\n" +
	"\x15ProcessPaymentRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\"g\n" +
	"\x16ProcessPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\xf8\x01\n" +
	"\x0ePaymentDetails\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x19\n" +
	"\brider_id\x18\x03 \x01(\tR\ariderId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"^\n" +
	"\rRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"]\n" +
	"\x0eRefundResponse\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"m\n" +
	"\x18GetDriverEarningsRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"\xd9\x01\n" +
	"\x0eDriverEarnings\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12!\n" +
	"\ftotal_earned\x18\x02 \x01(\x01R\vtotalEarned\x12\x1f\n" +
	"\vtotal_trips\x18\x03 \x01(\x05R\n" +
	"totalTrips\x12(\n" +
	"\x10average_per_trip\x18\x04 \x01(\x01R\x0eaveragePerTrip\x12\x1f\n" +
	"\vperiod_from\x18\x05 \x01(\tR\n" +
	"periodFrom\x12\x1b\n" +
	"\tperiod_to\x18\x06 \x01(\tR\bperiodTo2\x82\x03\n" +
	"\x0ePaymentService\x12N\n" +
	"\rCalculateFare\x12\x1d.payment.CalculateFareRequest\x1a\x1e.payment.CalculateFareResponse\x12Q\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\x12A\n" +
	"\n" +
	"GetPayment\x12\x1a.payment.GetPaymentRequest\x1a\x17.payment.PaymentDetails\x129\n" +
	"\x06Refund\x12\x16.payment.RefundRequest\x1a\x17.payment.RefundResponse\x12O\n" +
	"\x11GetDriverEarnings\x12!.payment.GetDriverEarningsRequest\x1a\x17.payment.DriverEarningsB'Z%github.com/taxxy/shared/proto/paymentb\x06proto3"

var (
	file_payment_payment_proto_rawDescOnce sync.Once
	file_payment_payment_proto_rawDescData []byte
)

func file_payment_payment_proto_rawDescGZIP() []byte {
	file_payment_payment_proto_rawDescOnce.Do(func() {
		file_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)))
	})
	return file_payment_payment_proto_rawDescData
}

var file_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_payment_payment_proto_goTypes = []any{
	(*CalculateFareRequest)(nil),     // 0: payment.CalculateFareRequest
	(*CalculateFareResponse)(nil),    // 1: payment.CalculateFareResponse
	(*ProcessPaymentRequest)(nil),    // 2: payment.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),   // 3: payment.ProcessPaymentResponse
	(*GetPaymentRequest)(nil),        // 4: payment.GetPaymentRequest
	(*PaymentDetails)(nil),           // 5: payment.PaymentDetails
	(*RefundRequest)(nil),            // 6: payment.RefundRequest
	(*RefundResponse)(nil),           // 7: payment.RefundResponse
	(*GetDriverEarningsRequest)(nil), // 8: payment.GetDriverEarningsRequest
	(*DriverEarnings)(nil),           // 9: payment.DriverEarnings
}
var file_payment_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.CalculateFare:input_type -> payment.CalculateFareRequest
	2, // 1: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	4, // 2: payment.PaymentService.GetPayment:input_type -> payment.GetPaymentRequest
	6, // 3: payment.PaymentService.Refund:input_type -> payment.RefundRequest
	8, // 4: payment.PaymentService.GetDriverEarnings:input_type -> payment.GetDriverEarningsRequest
	1, // 5: payment.PaymentService.CalculateFare:output_type -> payment.CalculateFareResponse
	3, // 6: payment.PaymentService.ProcessPayment:output_type -> payment.ProcessPaymentResponse
	5, // 7: payment.PaymentService.GetPayment:output_type -> payment.PaymentDetails
	7, // 8: payment.PaymentService.Refund:output_type -> payment.RefundResponse
	9, // 9: payment.PaymentService.GetDriverEarnings:output_type -> payment.DriverEarnings
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_payment_proto_init() }
func file_payment_payment_proto_init() {
	if File_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_payment_proto_goTypes,
		DependencyIndexes: file_payment_payment_proto_depIdxs,
		MessageInfos:      file_payment_payment_proto_msgTypes,
	}.Build()
	File_payment_payment_proto = out.File
	file_payment_payment_proto_goTypes = nil
	file_payment_payment_proto_depIdxs = nil
}
